---

- name: set apache servername
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(\n)#*(ServerName\b).*?$'
    replace: '\1\2 {{ ansible_fqdn }}'
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when: keystone_frontend == 'apache'

- name: see if wsgi config was copied already
  stat:
    path: /etc/httpd/conf.d/wsgi-keystone.conf
  register: wsgi_config_exists
  when: keystone_frontend == 'apache'

- name: copy wsgi conf file
  copy:
    src: /usr/share/keystone/wsgi-keystone.conf
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
    remote_src: yes
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when:
  - keystone_frontend == 'apache'
  - not wsgi_config_exists.stat.exists

- name: see if wsgi conf file has 35357
  shell: egrep -q 35357 /etc/httpd/conf.d/wsgi-keystone.conf &&
  become: yes
  register: keystone_wsgi_configuration_has_35357
  failed_when: "keystone_wsgi_configuration_has_35357.rc > 1"
  check_mode: no
  ignore_errors: "{{ ansible_check_mode }}"
  changed_when: no
  when:
  - keystone_frontend == 'apache'
  - wsgi_config_exists.stat.exists

- name: see if wsgi conf file has ssl
  shell: egrep -q SSLEngine /etc/httpd/conf.d/wsgi-keystone.conf
  become: yes
  register: keystone_wsgi_configuration_has_ssl
  failed_when: "keystone_wsgi_configuration_has_ssl.rc > 1"
  check_mode: no
  ignore_errors: "{{ ansible_check_mode }}"
  changed_when: no
  when:
  - keystone_frontend == 'apache'
  - wsgi_config_exists.stat.exists

- name: mutate wsgi conf file
  script: make-apache-cf.sh "{{ 1 if host_certs is defined else 0 }}"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when:
  - keystone_frontend == 'apache'
  - not wsgi_config_exists.stat.exists or ((keystone_wsgi_configuration_has_ssl.rc == 1) == (host_certs is defined)) or keystone_wsgi_configuration_has_35357.rc == 1
