---

- name: set apache servername
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '(\n)#*(ServerName\b).*?$'
    replace: '\1\2 {{ ansible_fqdn }}'
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when: keystone_frontend == 'apache'

- name: copy wsgi conf file
  copy:
    src: /usr/share/keystone/wsgi-keystone.conf
    dest: /etc/httpd/conf.d/wsgi-keystone.conf
    remote_src: yes
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when: keystone_frontend == 'apache'

- name: mutate wsgi conf file for ssl
  replace:
    path: /etc/httpd/conf.d/wsgi-keystone.conf
    regexp: "(</Directory>\n)"
    replace: "\\1    SSLEngine on\n    SSLCertificateFile /etc/keystone/private/{{ inventory_hostname_short }}.pem\n    SSLCertificateKeyFile /etc/keystone/private/{{ inventory_hostname_short }}.key\n    SSLCACertificateFile {{ local_ca_path }}\n"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when:
  - keystone_frontend == 'apache'
  - host_certs is defined

#- name: mutate httpd configuration too
#  file:
#    path: /etc/httpd/conf.d/ssl.conf
#    regexp: "localhost"
#    replace: "{{ ansible_hostname }}"
#  become: yes
#  ignore_errors: "{{ ansible_check_mode }}"
#  when:
#  - keystone_frontend == 'apache'
#  - host_certs is defined
