---

- name: Remove keystone packages
  yum:
        name:
        - memcached
        - python3-memcached
        - openstack-keystone
        - python3-openstackclient
        - centos-release-openstack-{{ keystone_version }}
        state: absent
  become: yes

- name: Remove cherrypy frontend for keystone
  yum:
        name:
        - python3-cherrypy
  become: yes
  when:
  - keystone_frontend == 'cherrypy'

- name: Remove apache frontend for keystone
  yum:
        name:
        - httpd
        - python3-mod_wsgi
  become: yes
  when:
  - keystone_frontend == 'apache'
