---

- name: see if firewalld running
  command: systemctl show firewalld  --property=ActiveState
  register: firewalld_running
  changed_when: no

- name: add keystone public
  firewalld:
    port: 5000/tcp
    permanent: true
    state: enabled
  become: yes
  register: keystone_public

- name: add keystone admin
  firewalld:
    port: 35357/tcp
    permanent: true
    state: enabled
  become: yes
  register: keystone_admin

- name: reload firewalld
  command: firewall-cmd --reload
  become: yes
  when:
  - keystone_admin.changed or keystone_public.changed
  - firewalld_running.stdout is search('=active')
