---
- meta: flush_handlers

- include: selinux.yml
- include: ssl.yml
- include: packages.yml
- include: cherrypy_wsgi.yml
- include: configuration.yml

- meta: flush_handlers

- include: bootstrap.yml

- include: start.yml
- include: provision.yml

#- include: tenants.yml
