---
- meta: flush_handlers

- import_tasks: selinux.yml
- import_tasks: ssl.yml
- import_tasks: make_out.yml
- import_tasks: packages.yml
- import_tasks: cherrypy_wsgi.yml
- import_tasks: configuration.yml
- import_tasks: apache_cf.yml

- meta: flush_handlers

- import_tasks: bootstrap.yml

- import_tasks: start.yml
- import_tasks: provision.yml

#- import_tasks: tenants.yml
