---

- name: Install mariadb
  yum:
    name:
    - mariadb
    - mariadb-server
    - python3-PyMySQL
    state: present
  become: yes
  when: keystone_backend == 'mysql'
  ignore_errors: "{{ ansible_check_mode }}"

- name: make mariadb configuration
  template:
    src: mycnf.j2
    dest: "/etc/my.cnf.d/openstack.cnf"
  become: yes
  when: keystone_backend == 'mysql'

- name: generate mariadb root pw if not set
  set_fact:
    mariadb_root_pass: "{{ mariadb_root_pass if mariadb_root_pass is defined else lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
    cacheable: yes
  delegate_to: localhost
  when: keystone_backend == 'mysql'

- name: generate keystone db pw if not set
  set_fact:
    keystone_db_pass: "{{ keystone_db_pass if keystone_db_pass is defined else lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
    cacheable: yes
  delegate_to: localhost
  when: keystone_backend == 'mysql'

- name: print generated mariadb password
  debug:
    msg: "mariadb root password {{ mariadb_root_pass }}"
  delegate_to: localhost
  when: keystone_backend == 'mysql'

- name: print generated keystone db password
  debug:
    msg: "keystone db password {{ keystone_db_pass }}"
  delegate_to: localhost
  when: keystone_backend == 'mysql'

- name: save mariadb passwords
  template: src=passwords.j2 dest="out/{{ inventory_hostname_short }}-mariadb-passwords" mode=0600
  delegate_to: localhost
  when: keystone_backend == 'mysql'
