---

# can't start/stop service if unit file not present.

- name: Install memcached
  become: yes
  yum:
    name:
    - memcached
    - python-memcached
    state: present

- name: Start memcached
  become: yes
  service: name=memcached state=started enabled=yes
  ignore_errors: "{{ ansible_check_mode }}"
