---

- include: tasteful.yml

- include: epel.yml

- include: openstack.yml

- include: mariadb.yml

- include: memcached.yml

- include: cherrypy.yml

- include: apache.yml

- name: Install keystone service and client
  become: yes
  yum: name="{{ item }}" state=present
  with_items:
  - openstack-keystone
  - python-openstackclient
  ignore_errors: "{{ ansible_check_mode }}"
