---

- include: tasteful.yml

- include: epel.yml

- include: openstack.yml

- include: mariadb.yml

- include: memcached.yml

- include: cherrypy.yml

- include: apache.yml

- name: Install keystone service and client
  become: yes
  yum:
    name:
    - openstack-keystone
    - python3-openstackclient
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
