---

- import_tasks: tasteful.yml

- import_tasks: epel.yml

- import_tasks: openstack.yml

- import_tasks: mariadb.yml

- import_tasks: memcached.yml

- import_tasks: cherrypy.yml

- import_tasks: apache.yml

- name: Install keystone service and client
  become: yes
  yum:
    name:
    - openstack-keystone
    - python3-openstackclient
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
