---
## needs shade 1.8 or better, on the control node.
##  I'm using shade 1.20 on degu. (degu:~mdw/wp/python.17)

- name: add project
  os_project:
     auth: &awsome_stuff
        auth_url: https://{{ ansible_fqdn }}:5000/v3/
        username: admin
        password: "{{ keystone_admin_password }}"
        project_name: admin
     state: "{{ item.state | default(omit) }}"
     name: "{{ item.name }}"
     description: "{{ item.description | default(omit) }}"
     domain_id: "{{ item.domain_id | default(omit) }}"
     validate_certs: yes
  delegate_to: 127.0.0.1
  with_items: "{{ openstack_keystone_projects }}"

#  os_user:
#? cloud ?
#    auth:
#      auth_url: https:
#      username: admin
#      password: xxx
#      project_name: xxx
#? domain ?
#    state: present
#    name: demo
#    password: xxx
#    update_password: on_create
#    domain: Default
#    validate_certs: yes
#    default_project: demo
#** password
#*** auth_url
#*** username
#*** password
#*** project_name
