---

- name: Start keystone
  become: yes
  systemd: name=keystone.target state=started enabled=yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: wait until started
  wait_for:
    port: 5000
    delay: 10
    sleep: 5
