---

- name: Install tasteful subset of the usual utilities
  yum:
        name: [ dmidecode, dump, ed, eject, ftp, hdparm,
          lsof, mailx, man, nc, parted, rsync, sos,
          tcpdump, traceroute, time, wget, words,
          pciutils,
          lynx, mlocate, xterm, xauth, strace, tar, sysstat, net-tools,
          bc, gdb, rcs, bind-utils, yum-utils ]
        state: present
  become: yes
  tags: tasteful-rpms
