---
# restore machine to a (mostly) pristine state

- import_tasks: stop.yml
- import_tasks: remove-my-cnf.yml
- import_tasks: remove-systemd-stuff.yml
- import_tasks: restore-firewall.yml
- import_tasks: erase-keystone-stuff.yml
- import_tasks: erase-ca-cert.yml
- import_tasks: erase-keystone-iam.yml
- import_tasks: erase-python-dependencies.yml
- import_tasks: erase-epel-too.yml
#- meta: flush_handlers
